# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: algorithms/algorithms.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'algorithms/algorithms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61lgorithms/algorithms.proto\x12\nalgorithms\"\x16\n\x05query\x12\r\n\x05query\x18\x01 \x01(\t\"\x1c\n\x08response\x12\x10\n\x08response\x18\x01 \x01(\t2E\n\x0fJournalAnalyzer\x12\x32\n\x07\x61nalyze\x12\x11.algorithms.query\x1a\x14.algorithms.responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'algorithms.algorithms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERY']._serialized_start=43
  _globals['_QUERY']._serialized_end=65
  _globals['_RESPONSE']._serialized_start=67
  _globals['_RESPONSE']._serialized_end=95
  _globals['_JOURNALANALYZER']._serialized_start=97
  _globals['_JOURNALANALYZER']._serialized_end=166
# @@protoc_insertion_point(module_scope)
