steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sdgp-mind/hindsight-algo', './python-backend']
images:
  - 'gcr.io/$PROJECT_ID/python-backend'
options:
  logging: CLOUD_LOGGING_ONLY
  # logs_bucket: 'gs://your-logs-bucket'
