steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sdgp-mind/hindsight-algo', './algorithms']
    env:
      - 'OPENAI_API_KEY=${_OPENAI_API_KEY}'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sdgp-mind/hindsight-algo']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'hindsight-algo-grpc',
      '--image', 'gcr.io/sdgp-mind/hindsight-algo',
      '--region', 'asia-south1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--execution-environment', 'gen2',
      '--use-http2',
      '--timeout', '300s',
      '--cpu', '1',
      '--memory', '512Mi' 
    ]

images:
  - 'gcr.io/sdgp-mind/hindsight-algo'

options:
  logging: CLOUD_LOGGING_ONLY
